spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: GithubId
            clientSecret: GithubSecret
          google:
            client-id: GoogleId
            client-secret: GoogleSecret
